---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: annotation-converter
  {{- include "helm_lib_module_labels" (list . (dict "app" "annotation-converter")) | nindent 2 }}
webhooks:
- name: annotation-converter.webhook.deckhouse.io
  admissionReviewVersions: ["v1", "v1beta1"]
  failurePolicy: Fail
  {{- if semverCompare ">=1.15" .Values.global.discovery.kubernetesVersion }}
  matchPolicy: Equivalent
  {{- end }}
  sideEffects: None
  timeoutSeconds: 10
  clientConfig:
    service:
      name: annotation-converter-webhook
      namespace: d8-monitoring
      path: "/mutate"
      {{- if semverCompare ">=1.15" .Values.global.discovery.kubernetesVersion }}
      port: 443
    {{- end }}
    caBundle: {{ .Values.extendedMonitoring.internal.webhookCert.ca | b64enc }}
  rules:
  - operations: [ "CREATE", "UPDATE" ]
    apiGroups: ["*"]
    apiVersions: ["*"]
    resources:
    - namespaces
    - deployments
    - statefulsets
    - daemonsets
    - cronjobs
    - ingresses
    - nodes
