---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    helm.sh/hook: post-upgrade, post-install
    helm.sh/hook-delete-policy: before-hook-creation
  name: annotation-converter-webhook
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "annotation-converter-webhook")) | nindent 2 }}
spec:
  minAvailable: {{ include "helm_lib_is_ha_to_value" (list . 1 0) }}
  selector:
    matchLabels:
      heritage: deckhouse
      module: {{ .Chart.Name }}
      app: annotation-converter-webhook
